// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.1
// source: proto/pubsub.proto

package pubsub

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Topics        []string               `protobuf:"bytes,3,rep,name=topics,proto3" json:"topics,omitempty"`
	Publisher     string                 `protobuf:"bytes,4,opt,name=publisher,proto3" json:"publisher,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_pubsub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pubsub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_pubsub_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Message) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *Message) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *Message) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type NewPublisherResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PubId         string                 `protobuf:"bytes,1,opt,name=pub_id,json=pubId,proto3" json:"pub_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewPublisherResponse) Reset() {
	*x = NewPublisherResponse{}
	mi := &file_proto_pubsub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewPublisherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewPublisherResponse) ProtoMessage() {}

func (x *NewPublisherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pubsub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewPublisherResponse.ProtoReflect.Descriptor instead.
func (*NewPublisherResponse) Descriptor() ([]byte, []int) {
	return file_proto_pubsub_proto_rawDescGZIP(), []int{1}
}

func (x *NewPublisherResponse) GetPubId() string {
	if x != nil {
		return x.PubId
	}
	return ""
}

type UnregisterPublisherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PubId         string                 `protobuf:"bytes,1,opt,name=pub_id,json=pubId,proto3" json:"pub_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterPublisherRequest) Reset() {
	*x = UnregisterPublisherRequest{}
	mi := &file_proto_pubsub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterPublisherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterPublisherRequest) ProtoMessage() {}

func (x *UnregisterPublisherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pubsub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterPublisherRequest.ProtoReflect.Descriptor instead.
func (*UnregisterPublisherRequest) Descriptor() ([]byte, []int) {
	return file_proto_pubsub_proto_rawDescGZIP(), []int{2}
}

func (x *UnregisterPublisherRequest) GetPubId() string {
	if x != nil {
		return x.PubId
	}
	return ""
}

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PubId         string                 `protobuf:"bytes,1,opt,name=pub_id,json=pubId,proto3" json:"pub_id,omitempty"`
	Topics        []string               `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_proto_pubsub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pubsub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_proto_pubsub_proto_rawDescGZIP(), []int{3}
}

func (x *PublishRequest) GetPubId() string {
	if x != nil {
		return x.PubId
	}
	return ""
}

func (x *PublishRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *PublishRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type NewSubscriberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BufferSize    int32                  `protobuf:"varint,1,opt,name=buffer_size,json=bufferSize,proto3" json:"buffer_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewSubscriberRequest) Reset() {
	*x = NewSubscriberRequest{}
	mi := &file_proto_pubsub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewSubscriberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewSubscriberRequest) ProtoMessage() {}

func (x *NewSubscriberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pubsub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewSubscriberRequest.ProtoReflect.Descriptor instead.
func (*NewSubscriberRequest) Descriptor() ([]byte, []int) {
	return file_proto_pubsub_proto_rawDescGZIP(), []int{4}
}

func (x *NewSubscriberRequest) GetBufferSize() int32 {
	if x != nil {
		return x.BufferSize
	}
	return 0
}

type NewSubscriberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubId         string                 `protobuf:"bytes,1,opt,name=sub_id,json=subId,proto3" json:"sub_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewSubscriberResponse) Reset() {
	*x = NewSubscriberResponse{}
	mi := &file_proto_pubsub_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewSubscriberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewSubscriberResponse) ProtoMessage() {}

func (x *NewSubscriberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pubsub_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewSubscriberResponse.ProtoReflect.Descriptor instead.
func (*NewSubscriberResponse) Descriptor() ([]byte, []int) {
	return file_proto_pubsub_proto_rawDescGZIP(), []int{5}
}

func (x *NewSubscriberResponse) GetSubId() string {
	if x != nil {
		return x.SubId
	}
	return ""
}

type UnregisterSubscriberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubId         string                 `protobuf:"bytes,1,opt,name=sub_id,json=subId,proto3" json:"sub_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterSubscriberRequest) Reset() {
	*x = UnregisterSubscriberRequest{}
	mi := &file_proto_pubsub_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterSubscriberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterSubscriberRequest) ProtoMessage() {}

func (x *UnregisterSubscriberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pubsub_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterSubscriberRequest.ProtoReflect.Descriptor instead.
func (*UnregisterSubscriberRequest) Descriptor() ([]byte, []int) {
	return file_proto_pubsub_proto_rawDescGZIP(), []int{6}
}

func (x *UnregisterSubscriberRequest) GetSubId() string {
	if x != nil {
		return x.SubId
	}
	return ""
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubId         string                 `protobuf:"bytes,1,opt,name=sub_id,json=subId,proto3" json:"sub_id,omitempty"`
	PubId         string                 `protobuf:"bytes,2,opt,name=pub_id,json=pubId,proto3" json:"pub_id,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_pubsub_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pubsub_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_pubsub_proto_rawDescGZIP(), []int{7}
}

func (x *SubscribeRequest) GetSubId() string {
	if x != nil {
		return x.SubId
	}
	return ""
}

func (x *SubscribeRequest) GetPubId() string {
	if x != nil {
		return x.PubId
	}
	return ""
}

func (x *SubscribeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type UnsubscribePublisherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubId         string                 `protobuf:"bytes,1,opt,name=sub_id,json=subId,proto3" json:"sub_id,omitempty"`
	PubId         string                 `protobuf:"bytes,2,opt,name=pub_id,json=pubId,proto3" json:"pub_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribePublisherRequest) Reset() {
	*x = UnsubscribePublisherRequest{}
	mi := &file_proto_pubsub_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribePublisherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribePublisherRequest) ProtoMessage() {}

func (x *UnsubscribePublisherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pubsub_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribePublisherRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribePublisherRequest) Descriptor() ([]byte, []int) {
	return file_proto_pubsub_proto_rawDescGZIP(), []int{8}
}

func (x *UnsubscribePublisherRequest) GetSubId() string {
	if x != nil {
		return x.SubId
	}
	return ""
}

func (x *UnsubscribePublisherRequest) GetPubId() string {
	if x != nil {
		return x.PubId
	}
	return ""
}

type UnsubscribeTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubId         string                 `protobuf:"bytes,1,opt,name=sub_id,json=subId,proto3" json:"sub_id,omitempty"`
	PubId         string                 `protobuf:"bytes,2,opt,name=pub_id,json=pubId,proto3" json:"pub_id,omitempty"`
	Topics        []string               `protobuf:"bytes,3,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeTopicRequest) Reset() {
	*x = UnsubscribeTopicRequest{}
	mi := &file_proto_pubsub_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeTopicRequest) ProtoMessage() {}

func (x *UnsubscribeTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pubsub_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeTopicRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeTopicRequest) Descriptor() ([]byte, []int) {
	return file_proto_pubsub_proto_rawDescGZIP(), []int{9}
}

func (x *UnsubscribeTopicRequest) GetSubId() string {
	if x != nil {
		return x.SubId
	}
	return ""
}

func (x *UnsubscribeTopicRequest) GetPubId() string {
	if x != nil {
		return x.PubId
	}
	return ""
}

func (x *UnsubscribeTopicRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

type TryConsumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubId         string                 `protobuf:"bytes,1,opt,name=sub_id,json=subId,proto3" json:"sub_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TryConsumeRequest) Reset() {
	*x = TryConsumeRequest{}
	mi := &file_proto_pubsub_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TryConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TryConsumeRequest) ProtoMessage() {}

func (x *TryConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pubsub_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TryConsumeRequest.ProtoReflect.Descriptor instead.
func (*TryConsumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_pubsub_proto_rawDescGZIP(), []int{10}
}

func (x *TryConsumeRequest) GetSubId() string {
	if x != nil {
		return x.SubId
	}
	return ""
}

type TryConsumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TryConsumeResponse) Reset() {
	*x = TryConsumeResponse{}
	mi := &file_proto_pubsub_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TryConsumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TryConsumeResponse) ProtoMessage() {}

func (x *TryConsumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pubsub_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TryConsumeResponse.ProtoReflect.Descriptor instead.
func (*TryConsumeResponse) Descriptor() ([]byte, []int) {
	return file_proto_pubsub_proto_rawDescGZIP(), []int{11}
}

func (x *TryConsumeResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *TryConsumeResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type KeepConsumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubId         string                 `protobuf:"bytes,1,opt,name=sub_id,json=subId,proto3" json:"sub_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepConsumeRequest) Reset() {
	*x = KeepConsumeRequest{}
	mi := &file_proto_pubsub_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepConsumeRequest) ProtoMessage() {}

func (x *KeepConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pubsub_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepConsumeRequest.ProtoReflect.Descriptor instead.
func (*KeepConsumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_pubsub_proto_rawDescGZIP(), []int{12}
}

func (x *KeepConsumeRequest) GetSubId() string {
	if x != nil {
		return x.SubId
	}
	return ""
}

type KeepConsumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepConsumeResponse) Reset() {
	*x = KeepConsumeResponse{}
	mi := &file_proto_pubsub_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepConsumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepConsumeResponse) ProtoMessage() {}

func (x *KeepConsumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pubsub_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepConsumeResponse.ProtoReflect.Descriptor instead.
func (*KeepConsumeResponse) Descriptor() ([]byte, []int) {
	return file_proto_pubsub_proto_rawDescGZIP(), []int{13}
}

func (x *KeepConsumeResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_proto_pubsub_proto protoreflect.FileDescriptor

const file_proto_pubsub_proto_rawDesc = "" +
	"\n" +
	"\x12proto/pubsub.proto\x12\x06pubsub\x1a\x1bgoogle/protobuf/empty.proto\"\x82\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x16\n" +
	"\x06topics\x18\x03 \x03(\tR\x06topics\x12\x1c\n" +
	"\tpublisher\x18\x04 \x01(\tR\tpublisher\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"-\n" +
	"\x14NewPublisherResponse\x12\x15\n" +
	"\x06pub_id\x18\x01 \x01(\tR\x05pubId\"3\n" +
	"\x1aUnregisterPublisherRequest\x12\x15\n" +
	"\x06pub_id\x18\x01 \x01(\tR\x05pubId\"S\n" +
	"\x0ePublishRequest\x12\x15\n" +
	"\x06pub_id\x18\x01 \x01(\tR\x05pubId\x12\x16\n" +
	"\x06topics\x18\x02 \x03(\tR\x06topics\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"7\n" +
	"\x14NewSubscriberRequest\x12\x1f\n" +
	"\vbuffer_size\x18\x01 \x01(\x05R\n" +
	"bufferSize\".\n" +
	"\x15NewSubscriberResponse\x12\x15\n" +
	"\x06sub_id\x18\x01 \x01(\tR\x05subId\"4\n" +
	"\x1bUnregisterSubscriberRequest\x12\x15\n" +
	"\x06sub_id\x18\x01 \x01(\tR\x05subId\"V\n" +
	"\x10SubscribeRequest\x12\x15\n" +
	"\x06sub_id\x18\x01 \x01(\tR\x05subId\x12\x15\n" +
	"\x06pub_id\x18\x02 \x01(\tR\x05pubId\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\"K\n" +
	"\x1bUnsubscribePublisherRequest\x12\x15\n" +
	"\x06sub_id\x18\x01 \x01(\tR\x05subId\x12\x15\n" +
	"\x06pub_id\x18\x02 \x01(\tR\x05pubId\"_\n" +
	"\x17UnsubscribeTopicRequest\x12\x15\n" +
	"\x06sub_id\x18\x01 \x01(\tR\x05subId\x12\x15\n" +
	"\x06pub_id\x18\x02 \x01(\tR\x05pubId\x12\x16\n" +
	"\x06topics\x18\x03 \x03(\tR\x06topics\"*\n" +
	"\x11TryConsumeRequest\x12\x15\n" +
	"\x06sub_id\x18\x01 \x01(\tR\x05subId\"O\n" +
	"\x12TryConsumeResponse\x12)\n" +
	"\amessage\x18\x01 \x01(\v2\x0f.pubsub.MessageR\amessage\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\"+\n" +
	"\x12KeepConsumeRequest\x12\x15\n" +
	"\x06sub_id\x18\x01 \x01(\tR\x05subId\"@\n" +
	"\x13KeepConsumeResponse\x12)\n" +
	"\amessage\x18\x01 \x01(\v2\x0f.pubsub.MessageR\amessage2\xf6\x05\n" +
	"\rPubsubService\x12D\n" +
	"\fNewPublisher\x12\x16.google.protobuf.Empty\x1a\x1c.pubsub.NewPublisherResponse\x12Q\n" +
	"\x13UnregisterPublisher\x12\".pubsub.UnregisterPublisherRequest\x1a\x16.google.protobuf.Empty\x129\n" +
	"\aPublish\x12\x16.pubsub.PublishRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\rNewSubscriber\x12\x1c.pubsub.NewSubscriberRequest\x1a\x1d.pubsub.NewSubscriberResponse\x12S\n" +
	"\x14UnregisterSubscriber\x12#.pubsub.UnregisterSubscriberRequest\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\tSubscribe\x12\x18.pubsub.SubscribeRequest\x1a\x16.google.protobuf.Empty\x12S\n" +
	"\x14UnsubscribePublisher\x12#.pubsub.UnsubscribePublisherRequest\x1a\x16.google.protobuf.Empty\x12K\n" +
	"\x10UnsubscribeTopic\x12\x1f.pubsub.UnsubscribeTopicRequest\x1a\x16.google.protobuf.Empty\x12C\n" +
	"\n" +
	"TryConsume\x12\x19.pubsub.TryConsumeRequest\x1a\x1a.pubsub.TryConsumeResponse\x12H\n" +
	"\vKeepConsume\x12\x1a.pubsub.KeepConsumeRequest\x1a\x1b.pubsub.KeepConsumeResponse0\x01B\x16Z\x14pkg/pb/pubsub;pubsubb\x06proto3"

var (
	file_proto_pubsub_proto_rawDescOnce sync.Once
	file_proto_pubsub_proto_rawDescData []byte
)

func file_proto_pubsub_proto_rawDescGZIP() []byte {
	file_proto_pubsub_proto_rawDescOnce.Do(func() {
		file_proto_pubsub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pubsub_proto_rawDesc), len(file_proto_pubsub_proto_rawDesc)))
	})
	return file_proto_pubsub_proto_rawDescData
}

var file_proto_pubsub_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_pubsub_proto_goTypes = []any{
	(*Message)(nil),                     // 0: pubsub.Message
	(*NewPublisherResponse)(nil),        // 1: pubsub.NewPublisherResponse
	(*UnregisterPublisherRequest)(nil),  // 2: pubsub.UnregisterPublisherRequest
	(*PublishRequest)(nil),              // 3: pubsub.PublishRequest
	(*NewSubscriberRequest)(nil),        // 4: pubsub.NewSubscriberRequest
	(*NewSubscriberResponse)(nil),       // 5: pubsub.NewSubscriberResponse
	(*UnregisterSubscriberRequest)(nil), // 6: pubsub.UnregisterSubscriberRequest
	(*SubscribeRequest)(nil),            // 7: pubsub.SubscribeRequest
	(*UnsubscribePublisherRequest)(nil), // 8: pubsub.UnsubscribePublisherRequest
	(*UnsubscribeTopicRequest)(nil),     // 9: pubsub.UnsubscribeTopicRequest
	(*TryConsumeRequest)(nil),           // 10: pubsub.TryConsumeRequest
	(*TryConsumeResponse)(nil),          // 11: pubsub.TryConsumeResponse
	(*KeepConsumeRequest)(nil),          // 12: pubsub.KeepConsumeRequest
	(*KeepConsumeResponse)(nil),         // 13: pubsub.KeepConsumeResponse
	(*emptypb.Empty)(nil),               // 14: google.protobuf.Empty
}
var file_proto_pubsub_proto_depIdxs = []int32{
	0,  // 0: pubsub.TryConsumeResponse.message:type_name -> pubsub.Message
	0,  // 1: pubsub.KeepConsumeResponse.message:type_name -> pubsub.Message
	14, // 2: pubsub.PubsubService.NewPublisher:input_type -> google.protobuf.Empty
	2,  // 3: pubsub.PubsubService.UnregisterPublisher:input_type -> pubsub.UnregisterPublisherRequest
	3,  // 4: pubsub.PubsubService.Publish:input_type -> pubsub.PublishRequest
	4,  // 5: pubsub.PubsubService.NewSubscriber:input_type -> pubsub.NewSubscriberRequest
	6,  // 6: pubsub.PubsubService.UnregisterSubscriber:input_type -> pubsub.UnregisterSubscriberRequest
	7,  // 7: pubsub.PubsubService.Subscribe:input_type -> pubsub.SubscribeRequest
	8,  // 8: pubsub.PubsubService.UnsubscribePublisher:input_type -> pubsub.UnsubscribePublisherRequest
	9,  // 9: pubsub.PubsubService.UnsubscribeTopic:input_type -> pubsub.UnsubscribeTopicRequest
	10, // 10: pubsub.PubsubService.TryConsume:input_type -> pubsub.TryConsumeRequest
	12, // 11: pubsub.PubsubService.KeepConsume:input_type -> pubsub.KeepConsumeRequest
	1,  // 12: pubsub.PubsubService.NewPublisher:output_type -> pubsub.NewPublisherResponse
	14, // 13: pubsub.PubsubService.UnregisterPublisher:output_type -> google.protobuf.Empty
	14, // 14: pubsub.PubsubService.Publish:output_type -> google.protobuf.Empty
	5,  // 15: pubsub.PubsubService.NewSubscriber:output_type -> pubsub.NewSubscriberResponse
	14, // 16: pubsub.PubsubService.UnregisterSubscriber:output_type -> google.protobuf.Empty
	14, // 17: pubsub.PubsubService.Subscribe:output_type -> google.protobuf.Empty
	14, // 18: pubsub.PubsubService.UnsubscribePublisher:output_type -> google.protobuf.Empty
	14, // 19: pubsub.PubsubService.UnsubscribeTopic:output_type -> google.protobuf.Empty
	11, // 20: pubsub.PubsubService.TryConsume:output_type -> pubsub.TryConsumeResponse
	13, // 21: pubsub.PubsubService.KeepConsume:output_type -> pubsub.KeepConsumeResponse
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_pubsub_proto_init() }
func file_proto_pubsub_proto_init() {
	if File_proto_pubsub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pubsub_proto_rawDesc), len(file_proto_pubsub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pubsub_proto_goTypes,
		DependencyIndexes: file_proto_pubsub_proto_depIdxs,
		MessageInfos:      file_proto_pubsub_proto_msgTypes,
	}.Build()
	File_proto_pubsub_proto = out.File
	file_proto_pubsub_proto_goTypes = nil
	file_proto_pubsub_proto_depIdxs = nil
}
