// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.27.1
// source: proto/pubsub.proto

package pubsub

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PubsubService_NewPublisher_FullMethodName         = "/pubsub.PubsubService/NewPublisher"
	PubsubService_UnregisterPublisher_FullMethodName  = "/pubsub.PubsubService/UnregisterPublisher"
	PubsubService_Publish_FullMethodName              = "/pubsub.PubsubService/Publish"
	PubsubService_NewSubscriber_FullMethodName        = "/pubsub.PubsubService/NewSubscriber"
	PubsubService_UnregisterSubscriber_FullMethodName = "/pubsub.PubsubService/UnregisterSubscriber"
	PubsubService_Subscribe_FullMethodName            = "/pubsub.PubsubService/Subscribe"
	PubsubService_UnsubscribePublisher_FullMethodName = "/pubsub.PubsubService/UnsubscribePublisher"
	PubsubService_UnsubscribeTopic_FullMethodName     = "/pubsub.PubsubService/UnsubscribeTopic"
	PubsubService_TryConsume_FullMethodName           = "/pubsub.PubsubService/TryConsume"
	PubsubService_KeepConsume_FullMethodName          = "/pubsub.PubsubService/KeepConsume"
)

// PubsubServiceClient is the client API for PubsubService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PubsubServiceClient interface {
	NewPublisher(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NewPublisherResponse, error)
	UnregisterPublisher(ctx context.Context, in *UnregisterPublisherRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	NewSubscriber(ctx context.Context, in *NewSubscriberRequest, opts ...grpc.CallOption) (*NewSubscriberResponse, error)
	UnregisterSubscriber(ctx context.Context, in *UnregisterSubscriberRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UnsubscribePublisher(ctx context.Context, in *UnsubscribePublisherRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UnsubscribeTopic(ctx context.Context, in *UnsubscribeTopicRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	TryConsume(ctx context.Context, in *TryConsumeRequest, opts ...grpc.CallOption) (*TryConsumeResponse, error)
	KeepConsume(ctx context.Context, in *KeepConsumeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[KeepConsumeResponse], error)
}

type pubsubServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPubsubServiceClient(cc grpc.ClientConnInterface) PubsubServiceClient {
	return &pubsubServiceClient{cc}
}

func (c *pubsubServiceClient) NewPublisher(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NewPublisherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewPublisherResponse)
	err := c.cc.Invoke(ctx, PubsubService_NewPublisher_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pubsubServiceClient) UnregisterPublisher(ctx context.Context, in *UnregisterPublisherRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PubsubService_UnregisterPublisher_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pubsubServiceClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PubsubService_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pubsubServiceClient) NewSubscriber(ctx context.Context, in *NewSubscriberRequest, opts ...grpc.CallOption) (*NewSubscriberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewSubscriberResponse)
	err := c.cc.Invoke(ctx, PubsubService_NewSubscriber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pubsubServiceClient) UnregisterSubscriber(ctx context.Context, in *UnregisterSubscriberRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PubsubService_UnregisterSubscriber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pubsubServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PubsubService_Subscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pubsubServiceClient) UnsubscribePublisher(ctx context.Context, in *UnsubscribePublisherRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PubsubService_UnsubscribePublisher_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pubsubServiceClient) UnsubscribeTopic(ctx context.Context, in *UnsubscribeTopicRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PubsubService_UnsubscribeTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pubsubServiceClient) TryConsume(ctx context.Context, in *TryConsumeRequest, opts ...grpc.CallOption) (*TryConsumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TryConsumeResponse)
	err := c.cc.Invoke(ctx, PubsubService_TryConsume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pubsubServiceClient) KeepConsume(ctx context.Context, in *KeepConsumeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[KeepConsumeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PubsubService_ServiceDesc.Streams[0], PubsubService_KeepConsume_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[KeepConsumeRequest, KeepConsumeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PubsubService_KeepConsumeClient = grpc.ServerStreamingClient[KeepConsumeResponse]

// PubsubServiceServer is the server API for PubsubService service.
// All implementations must embed UnimplementedPubsubServiceServer
// for forward compatibility.
type PubsubServiceServer interface {
	NewPublisher(context.Context, *emptypb.Empty) (*NewPublisherResponse, error)
	UnregisterPublisher(context.Context, *UnregisterPublisherRequest) (*emptypb.Empty, error)
	Publish(context.Context, *PublishRequest) (*emptypb.Empty, error)
	NewSubscriber(context.Context, *NewSubscriberRequest) (*NewSubscriberResponse, error)
	UnregisterSubscriber(context.Context, *UnregisterSubscriberRequest) (*emptypb.Empty, error)
	Subscribe(context.Context, *SubscribeRequest) (*emptypb.Empty, error)
	UnsubscribePublisher(context.Context, *UnsubscribePublisherRequest) (*emptypb.Empty, error)
	UnsubscribeTopic(context.Context, *UnsubscribeTopicRequest) (*emptypb.Empty, error)
	TryConsume(context.Context, *TryConsumeRequest) (*TryConsumeResponse, error)
	KeepConsume(*KeepConsumeRequest, grpc.ServerStreamingServer[KeepConsumeResponse]) error
	mustEmbedUnimplementedPubsubServiceServer()
}

// UnimplementedPubsubServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPubsubServiceServer struct{}

func (UnimplementedPubsubServiceServer) NewPublisher(context.Context, *emptypb.Empty) (*NewPublisherResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NewPublisher not implemented")
}
func (UnimplementedPubsubServiceServer) UnregisterPublisher(context.Context, *UnregisterPublisherRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterPublisher not implemented")
}
func (UnimplementedPubsubServiceServer) Publish(context.Context, *PublishRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedPubsubServiceServer) NewSubscriber(context.Context, *NewSubscriberRequest) (*NewSubscriberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NewSubscriber not implemented")
}
func (UnimplementedPubsubServiceServer) UnregisterSubscriber(context.Context, *UnregisterSubscriberRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterSubscriber not implemented")
}
func (UnimplementedPubsubServiceServer) Subscribe(context.Context, *SubscribeRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedPubsubServiceServer) UnsubscribePublisher(context.Context, *UnsubscribePublisherRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UnsubscribePublisher not implemented")
}
func (UnimplementedPubsubServiceServer) UnsubscribeTopic(context.Context, *UnsubscribeTopicRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UnsubscribeTopic not implemented")
}
func (UnimplementedPubsubServiceServer) TryConsume(context.Context, *TryConsumeRequest) (*TryConsumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TryConsume not implemented")
}
func (UnimplementedPubsubServiceServer) KeepConsume(*KeepConsumeRequest, grpc.ServerStreamingServer[KeepConsumeResponse]) error {
	return status.Error(codes.Unimplemented, "method KeepConsume not implemented")
}
func (UnimplementedPubsubServiceServer) mustEmbedUnimplementedPubsubServiceServer() {}
func (UnimplementedPubsubServiceServer) testEmbeddedByValue()                       {}

// UnsafePubsubServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PubsubServiceServer will
// result in compilation errors.
type UnsafePubsubServiceServer interface {
	mustEmbedUnimplementedPubsubServiceServer()
}

func RegisterPubsubServiceServer(s grpc.ServiceRegistrar, srv PubsubServiceServer) {
	// If the following call panics, it indicates UnimplementedPubsubServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PubsubService_ServiceDesc, srv)
}

func _PubsubService_NewPublisher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubsubServiceServer).NewPublisher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PubsubService_NewPublisher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubsubServiceServer).NewPublisher(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PubsubService_UnregisterPublisher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterPublisherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubsubServiceServer).UnregisterPublisher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PubsubService_UnregisterPublisher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubsubServiceServer).UnregisterPublisher(ctx, req.(*UnregisterPublisherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PubsubService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubsubServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PubsubService_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubsubServiceServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PubsubService_NewSubscriber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewSubscriberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubsubServiceServer).NewSubscriber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PubsubService_NewSubscriber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubsubServiceServer).NewSubscriber(ctx, req.(*NewSubscriberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PubsubService_UnregisterSubscriber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterSubscriberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubsubServiceServer).UnregisterSubscriber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PubsubService_UnregisterSubscriber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubsubServiceServer).UnregisterSubscriber(ctx, req.(*UnregisterSubscriberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PubsubService_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubsubServiceServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PubsubService_Subscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubsubServiceServer).Subscribe(ctx, req.(*SubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PubsubService_UnsubscribePublisher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsubscribePublisherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubsubServiceServer).UnsubscribePublisher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PubsubService_UnsubscribePublisher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubsubServiceServer).UnsubscribePublisher(ctx, req.(*UnsubscribePublisherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PubsubService_UnsubscribeTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsubscribeTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubsubServiceServer).UnsubscribeTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PubsubService_UnsubscribeTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubsubServiceServer).UnsubscribeTopic(ctx, req.(*UnsubscribeTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PubsubService_TryConsume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TryConsumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubsubServiceServer).TryConsume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PubsubService_TryConsume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubsubServiceServer).TryConsume(ctx, req.(*TryConsumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PubsubService_KeepConsume_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(KeepConsumeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PubsubServiceServer).KeepConsume(m, &grpc.GenericServerStream[KeepConsumeRequest, KeepConsumeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PubsubService_KeepConsumeServer = grpc.ServerStreamingServer[KeepConsumeResponse]

// PubsubService_ServiceDesc is the grpc.ServiceDesc for PubsubService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PubsubService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pubsub.PubsubService",
	HandlerType: (*PubsubServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewPublisher",
			Handler:    _PubsubService_NewPublisher_Handler,
		},
		{
			MethodName: "UnregisterPublisher",
			Handler:    _PubsubService_UnregisterPublisher_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _PubsubService_Publish_Handler,
		},
		{
			MethodName: "NewSubscriber",
			Handler:    _PubsubService_NewSubscriber_Handler,
		},
		{
			MethodName: "UnregisterSubscriber",
			Handler:    _PubsubService_UnregisterSubscriber_Handler,
		},
		{
			MethodName: "Subscribe",
			Handler:    _PubsubService_Subscribe_Handler,
		},
		{
			MethodName: "UnsubscribePublisher",
			Handler:    _PubsubService_UnsubscribePublisher_Handler,
		},
		{
			MethodName: "UnsubscribeTopic",
			Handler:    _PubsubService_UnsubscribeTopic_Handler,
		},
		{
			MethodName: "TryConsume",
			Handler:    _PubsubService_TryConsume_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "KeepConsume",
			Handler:       _PubsubService_KeepConsume_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/pubsub.proto",
}
